import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer | PropKnown Infra Pvt Ltd",
  description: "Disclaimer for PropKnown AI valuations and property information.",
};

export default function DisclaimerPage() {
  return (
    <div className="pt-32 pb-20 bg-brand-black min-h-screen">
      <div className="max-w-3xl mx-auto px-6">
        <h1 className="text-3xl font-bold text-white mb-2" style={{ fontFamily: "Georgia, serif" }}>Disclaimer</h1>
        <p className="text-zinc-500 text-sm mb-10">Last updated: June 2026</p>
        <div className="space-y-6 text-zinc-400 leading-relaxed">
          <section>
            <h2 className="text-white text-lg font-semibold mb-2">AI Valuations</h2>
            <p>All property valuations, price forecasts, rental yields, and investment scores on this website are generated by AI (JARVIS) for informational purposes only. They are indicative estimates based on historical data and market trends. They do not constitute a certified valuation, legal advice, or a guarantee of future performance.</p>
          </section>
          <section>
            <h2 className="text-white text-lg font-semibold mb-2">RERA Verification</h2>
            <p>RERA and HMDA registration numbers shown on listings are provided by sellers/developers and believed to be accurate. PropKnown strongly recommends independently verifying all RERA details at <a href="https://rera.telangana.gov.in" target="_blank" rel="noopener noreferrer" className="underline" style={{ color: "#C9A24B" }}>rera.telangana.gov.in</a> before making any investment decision.</p>
          </section>
          <section>
            <h2 className="text-white text-lg font-semibold mb-2">No Guarantee of Transaction</h2>
            <p>Listing a property on PropKnown does not guarantee a sale, purchase, or rental transaction. PropKnown facilitates connections between buyers and sellers but is not a party to any transaction. All deals are subject to independent legal due diligence.</p>
          </section>
          <section>
            <h2 className="text-white text-lg font-semibold mb-2">External Links</h2>
            <p>This website may contain links to external websites. PropKnown is not responsible for the content, accuracy, or privacy practices of any external site.</p>
          </section>
          <section>
            <h2 className="text-white text-lg font-semibold mb-2">Contact</h2>
            <p>For questions about this disclaimer: <a href="mailto:kiranpropservices@gmail.com" className="underline" style={{ color: "#C9A24B" }}>kiranpropservices@gmail.com</a></p>
          </section>
        </div>
      </div>
    </div>
  );
}
